enum CategoryMap {
	common = 0x00,
	bgcommon = 0x01,
	bg = 0x02,
	cut = 0x03,
	chara = 0x04,
	shader = 0x05,
	ui = 0x06,
	sound = 0x07,
	vfx = 0x08,
	ui_script = 0x09,
	exd = 0x0a,
	game_script = 0x0b,
	music = 0x0c,
	sqpack_test = 0x12,
	debug = 0x13,
}

const Category: Record<string, keyof typeof CategoryMap> = {
	COMMON: 'common',
	BG_COMMON: 'bgcommon',
	BG: 'bg',
	CUT: 'cut',
	CHARA: 'chara',
	SHADER: 'shader',
	UI: 'ui',
	SOUND: 'sound',
	VFX: 'vfx',
	UI_SCRIPT: 'ui_script',
	EXD: 'exd',
	GAME_SCRIPT: 'game_script',
	MUSIC: 'music',
	SQPACK_TEST: 'sqpack_test',
	DEBUG: 'debug',
}
